# Stage 1: Build React
FROM node:20 AS build
WORKDIR /app
COPY Frontend/frontendApi/package*.json ./
RUN npm install
COPY Frontend/ ./
RUN npm run build

# Stage 2: Servir con Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]