# Stage 1: Build Vite React
FROM node:20 AS build
WORKDIR /app

COPY Frontend/frontendApi/package*.json ./
RUN npm install

COPY Frontend/frontendApi/ ./
RUN npm run build

# Stage 2: Servir con Nginx
FROM nginx:stable-alpine

# Copiar build de Vite
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración personalizada de Nginx
COPY Frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]