apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2   # 🔥 autoescalable base
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: animales-backend:latest   # ⚠️ tu imagen
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc