# DockerfileBackend
FROM python:3.11-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de backend
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install python-multipart
    
# Exponer puerto (solo interno si quieres)
EXPOSE 8000

# Comando para iniciar FastAPI
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]